version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-nodejs
    container_name: mi-app-nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
